# Generated by Django 2.2.13 on 2024-04-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handoutclassresponse',
            name='color',
            field=models.CharField(choices=[('green', 'Grøn'), ('yellow', 'Gul'), ('red', 'Rød'), ('blue', 'Blå')], default='blue', max_length=10),
        ),
    ]
