# Generated by Django 2.2.13 on 2024-05-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0002_auto_20240411_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handoutclassresponse',
            name='color',
            field=models.CharField(choices=[('green', 'Grøn'), ('yellow', 'Gul'), ('red', 'Rød'), ('blue', 'Blå')], default='green', max_length=10),
        ),
    ]
