# Generated by Django 2.2.13 on 2020-10-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipant',
            name='status',
            field=models.CharField(choices=[('yes', 'Kommer'), ('no', 'Kommer ikke')], max_length=10, verbose_name='Svar'),
        ),
    ]
