# Generated by Django 2.2.13 on 2020-10-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipant',
            name='status',
            field=models.CharField(choices=[('yes', 'Kommer'), ('no', 'Kommer ikke'), ('sandwich1', 'Lakse sandwich'), ('sandwich2', 'italiensk pølse sandwich'), ('sandwich3', 'Kylling/bacon sandwich'), ('sandwich4', 'Roastbeef sandwich'), ('sandwich5', 'Vegansk sandwich')], max_length=10, verbose_name='Svar'),
        ),
    ]
