# Generated by Django 2.2.13 on 2020-11-01 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tutor', '0002_tutorprofile_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='BallotLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('url', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.TutorProfile')),
            ],
        ),
    ]
