# vim: set fileencoding=utf8:
FIRST_NAME = ( u'Aleksander', u'Alex', u'Alexander', u'Allan', u'Amanda',
u'Anders', u'Andreas', u'Anette', u'Anja', u'Anna', u'Anne', u'Asbjørn',
u'Asger', u'Aske', u'Astrid', u'Benjamin', u'Bjarke', u'Bjørn', u'Bo',
u'Brian', u'Camilla', u'Carsten', u'Casper', u'Cecilie', u'Chris',
u'Christian', u'Christina', u'Christoffer', u'Christopher', u'Claus',
u'Daniel', u'David', u'Dennis', u'Ebbe', u'Elisabeth', u'Emil', u'Emma',
u'Erik', u'Esben', u'Fie', u'Filip', u'Frank', u'Frederik', u'Glen', u'Hans',
u'Helene', u'Henriette', u'Henrik', u'Hjalte', u'Ida', u'Jacob', u'Jais',
u'Jakob', u'Jan', u'Jens', u'Jeppe', u'Jesper', u'Jimmi', u'Joachim', u'Johan',
u'Johannes', u'John', u'Jon', u'Jonas', u'Jonathan', u'Julia', u'Julie',
u'Karen', u'Karsten', u'Kasper', u'Katrin', u'Katrine', u'Kenneth', u'Kevin',
u'Kim', u'Kirsten', u'Kirstine', u'Klaus', u'Kristian', u'Kristina',
u'Kristoffer', u'Kåre', u'Lars', u'Lasse', u'Laura', u'Laurits', u'Lea',
u'Lennart', u'Line', u'Louis', u'Louise', u'Lukas', u'Lærke', u'Mads',
u'Magnus', u'Maiken', u'Maja', u'Malene', u'Marc', u'Marcus', u'Maria',
u'Marie', u'Mark', u'Martin', u'Mathias', u'Mathilde', u'Matias', u'Mette',
u'Mia', u'Michael', u'Michelle', u'Mikkel', u'Mohammad', u'Morten', u'Nadia',
u'Nanna', u'Nick', u'Nicki', u'Nicklas', u'Nicolai', u'Nicolaj', u'Niels',
u'Nikolaj', u'Nils', u'Nina', u'Ole', u'Peder', u'Per', u'Pernille', u'Peter',
u'Philip', u'Poul', u'Rasmus', u'Rene', u'René', u'Rikke', u'Rune', u'Sara',
u'Sebastian', u'Signe', u'Simon', u'Sofie', u'Steen', u'Stefan', u'Steffen',
u'Stine', u'Sune', u'Svend', u'Søren', u'Thanh', u'Thomas', u'Thor',
u'Thorbjørn', u'Tobias', u'Torsten', u'Trine', u'Troels', u'Tue', u'Uffe',
u'Ulrik', u'Victor', u'William' )

LAST_NAME = ( u'Aagaard', u'Aarup', u'Aastrup', u'Abildgaard', u'Adler',
u'Agersnap', u'Al', u'Alexander', u'Andersen', u'Andreas', u'Andreasen',
u'Anh', u'Bach', u'Bagge', u'Bak', u'Bali', u'Balle', u'Bang', u'Bay', u'Bech',
u'Beck', u'Berg', u'Bering', u'Bertelsen', u'Birch', u'Birk', u'Bjarni',
u'Bjerg', u'Bjerre', u'Bjerregaard', u'Bjerrum', u'Bjørn', u'Blach', u'Bo',
u'Bobach', u'Bohn', u'Boisen', u'Boje', u'Bonde', u'Borre', u'Borup',
u'Brandt', u'Brink', u'Brixen', u'Bruun', u'Bruus', u'Brygger', u'Buch',
u'Bue', u'Buhl', u'Bundgaard', u'Busch', u'Bøgh', u'Carlsen', u'Carstensen',
u'Christensen', u'Christian', u'Christiansen', u'Clausen', u'Colding', u'Dahl',
u'Dalgaard', u'Dalsgaard', u'Dam', u'Damgaard', u'Daniel', u'David', u'Ditlev',
u'Dybdahl', u'Elisabeth', u'Emil', u'Eriksen', u'Eskildsen', u'Fabricius',
u'Fischer', u'Flansmose', u'Flyvholm', u'Frandsen', u'Frank', u'Frederik',
u'Frederiksen', u'Friis', u'Funch', u'Fyhn', u'Færgemand', u'Gade', u'Geer',
u'Glavind', u'Gottenborg', u'Gram', u'Graversen', u'Gravgaard', u'Green',
u'Gregersen', u'Grøn', u'Grønbæk', u'Grønne', u'Guldborg', u'Haahr', u'Hald',
u'Halkjær', u'Hammer', u'Hanghøj', u'Hansen', u'Harder', u'Hartvig',
u'Haugaard', u'Have', u'Hedegaard', u'Helbo', u'Henneberg', u'Henriksen',
u'Hermansen', u'Hjorth', u'Holm', u'Holst', u'Hougaard', u'Houlberg',
u'Hovmand', u'Hviid', u'Hvilshøj', u'Høgh', u'Høj', u'Høy', u'Høyer',
u'Ingemann', u'Iversen', u'Jacob', u'Jacobsen', u'Jakob', u'Jakobsen', u'Jan',
u'Jegstrup', u'Jensen', u'Jeppesen', u'Jepsen', u'Jespersen', u'Jessen',
u'Johannes', u'Johansen', u'John', u'Juhl', u'Junker', u'Just', u'Juul',
u'Jørgensen', u'Jürgen', u'Kallestrup', u'Kamp', u'Katharina', u'Kathrine',
u'Katrine', u'Kiilerich', u'Kirk', u'Kjeldgaard', u'Kjær', u'Kjærgaard',
u'Knudsen', u'Koch', u'Korsgaard', u'Krabbe', u'Kristensen', u'Kristian',
u'Kristiansen', u'Krogh', u'Kruse', u'Kryger', u'Krüger', u'Kudsk', u'Kær',
u'Langeland', u'Larsen', u'Lassen', u'Lau', u'Lauridsen', u'Laursen',
u'Laustsen', u'Le', u'Lenvig', u'Linding', u'Lissner', u'Ljungdahl', u'Loft',
u'Lund', u'Lykke', u'Lyngby', u'M', u'Madsen', u'Mahmoud', u'Marcussen',
u'Maria', u'Marie', u'Markussen', u'Martin', u'Mathias', u'Mathiasen', u'Max',
u'Medum', u'Michael', u'Michelsen', u'Mikkelsen', u'Moeslund', u'Mogensen',
u'Mohammad', u'Mortensen', u'Munch', u'Munk', u'Mølgaard', u'Møller',
u'Nedergaard', u'Nguyen', u'Nicolaj', u'Nielsen', u'Niemann', u'Nissen',
u'Nygaard', u'Nyholm', u'Nørgaard', u'Nørregaard', u'Nørtoft', u'Ole',
u'Olesen', u'Olsen', u'Overgaard', u'Patricia', u'Pedersen', u'Peter',
u'Petersen', u'Philbert', u'Philip', u'Poulsen', u'Qvist', u'Rask',
u'Rasmussen', u'Refsgaard', u'Revsgaard', u'Riis', u'Rohde', u'Rolighed',
u'Rosenberg', u'Rosendal', u'Runge', u'Rønlev', u'Sand', u'Sander', u'Schmidt',
u'Schou', u'Schultz', u'Schulz', u'Schwartz', u'Sejr', u'Siggaard',
u'Simonsen', u'Skipper', u'Skov', u'Skovgaard', u'Skovlund', u'Skovsen',
u'Skytte', u'Skyum', u'Slot', u'Sofie', u'Sommer', u'Steen', u'Stefan',
u'Steffensen', u'Stensgaard', u'Stephansen', u'Storgaard', u'Strand-Holm',
u'Strange', u'Svane', u'Svendsen', u'Svingel', u'Sylvester', u'Søgaard',
u'Søndergaard', u'Sørensen', u'Terpager', u'Thalund', u'Therkelsen',
u'Thomsen', u'Thor', u'Thorsen', u'Thorup', u'Thygesen', u'Thyssen', u'Toft',
u'Tofte', u'Torp', u'Tran', u'Tranberg', u'Trelborg', u'Troelsen',
u'Udengaard', u'Valdemar', u'Vallaee', u'Vang', u'Vendelbo', u'Vestergaard',
u'Villadsen', u'Vilstrup', u'Vinther', u'Vu', u'Walther', u'Westergaard',
u'Wiese', u'Winther', u'Zacho', u'Øllegaard', u'Østergaard', )

STREET = (
u'Aldersrovej', u'Amaliegade', u'Askevej', u'Bellisvej', u'Bentesvej',
u'Bissensgade', u'Brendstrupgårdsvej', u'Bronzealdervænget', u'Børglumvej',
u'Bülowsgade', u'Carit Etlars Vej', u'Dalgas Avenue', u'Damagervej',
u'Dortesvej', u'Dybbølvej', u'Efterårsvej', u'Elstedhøj', u'Emmasvej',
u'Enghavevej', u'Engskovbakken', u'Fasanvej', u'Finderupvej', u'Fjældevænget',
u'Fredericiagade', u'Fuglesangs Alle', u'Fynsgade', u'Grenåvej',
u'Grete Løchtes Gade', u'Grøfthøjparken', u'Grøndalsvej', u'Grønnegade',
u'Gudrunsvej', u'Guldsmedgade', u'Gøteborg Allé', u'H. C. Ørstedsvej',
u'Havkærvænget', u'Hedemannsgade', u'Helsingforsgade', u'Horsensgade',
u'Hovedgaden', u'Ingersvej', u'Ivar Huitfeldts Gade', u'Janesvej',
u'Jens Baggesens Vej', u'Jens Baggesensvej', u'Jægergårdsgade',
u'Kaj Munks Vej', u'Kantorvænget', u'Kappelvænget', u'Karetmagertoften',
u'Kaserneboulevarden', u'Kirkevænget', u'Kirsebærhaven', u'Klokkerfaldet',
u'Klosterport', u'Kløvermarksvej', u'Knudrisgade', u'Ladefogedvej',
u'Langelandsgade', u'Langenæs Allé', u'Lavritsdalsvej', u'Lottesvej',
u'Marselis Boulevard', u'Marstrandsgade', u'Mejlgade', u'Møllevangs Alle',
u'Nordborggade', u'Nordlandsvej', u'Ny Munkegade', u'Nyvangsvej', u'Næringen',
u'Nøragervej', u'Nørrebrogade', u'Oddervej', u'Olof Palmes Allé',
u'Ormslevvej', u'Peder Skrams Gade', u'Platanvej', u'Randersvej',
u'Regenburgsgade', u'Risdalsvej', u'Ryhavevej', u'Ryvej', u'Samsøgade',
u'Silkeborgvej', u'Sjællandsgade', u'Skanderborgvej', u'Skejby Vænge',
u'Skejbygaardsvej', u'Skejbygårdsvej', u'Skejbyparken', u'Skolegade',
u'Skolevej', u'Skovvejen', u'Snogebæksvej', u'Solbakken', u'Spobjergvej',
u'Stavnsvej', u'Steinmannsgade', u'Strandvejen', u'Søhøjen', u'Søndervangen',
u'Søndre Ringgade', u'Thunøgade', u'Tjelevej', u'Torpevænget', u'Tousvej',
u'Tranekærvej', u'Trillegårdsvej', u'Trøjborgvej', u'Tøndergade',
u'Vesterbrogade', u'Vestergade', u'Vestervang', u'Vestre Ringgade',
u'Viborgvej', u'Vidtskuevej', u'Vintervej', u'Åboulevarden', u'Åhusene',
u'Åparken', u'Østboulevarden', u'Østervænget', )

CITY = (
u'8000 Aarhus C', u'8200 Aarhus N', u'8210 Aarhus V', u'8220 Brabrand',
u'8230 Åbyhøj', u'8240 Risskov', u'8250 Egå', u'8260 Viby J', u'8270 Højbjerg',
u'8300 Odder', u'8310 Tranbjerg', u'8320 Åbyhøj', u'8330 Beder',
u'8340 Malling', u'8350 Hundslund', u'8361 Hasselager', u'8362 Hørning',
u'8381 Tilst', u'8382 Hinnerup', u'8400 Ebeltoft', u'8410 Rønde',
u'8450 Hammel', u'8462 Harlev', u'8464 Galten', u'8471 Sabro', u'8472 Sporup',
u'8500 Grenå', u'8520 Lystrup', u'8530 Hjortshøj', u'8541 Skødstrup',
u'8543 Hornslet', u'8544 Moerke', u'8560 Kolind', u'8585 Glesborg',
u'8586 Ørum Djurs', u'8600 Silkeborg', u'8660 Skanderborg', u'8700 Horsens',
u'8721 Århus V', u'8723 Løsning', u'8740 Brædstrup', u'8751 Gedved',
u'8783 Hornsyld', u'8800 Viborg', u'8830 Tjele', u'8831 Løgstrup',
u'8832 Skals', u'8840 Rødkærsbro', u'8850 Bjerringbro', u'8860 Ulstrup',
u'8870 Langå', u'8882 Fårvang', u'8900 Randers C', u'8920 Randers NV',
u'8930 Randers NØ', u'8940 Randers SV', u'8960 Randers SØ', u'8981 Spentrup',
u'8983 Gjerlev', u'9000 Aalborg', )

GROUP = (
#(u'alle', u'Alle tutorer'),
(u'best', u'Bestyrelse'),
(u'buret', u'Buret'),
(u'cslab', u'CS-labrundvisning'),
(u'csdias', u'Dias - CS'),
(u'ifadias', u'Dias - IFA'),
(u'matdias', u'Dias - IMF'),
(u'evalueringer', u'Evalueringer'),
(u'hytter', u'Hytter'),
(u'hoestfest', u'Høstfest'),
(u'ifalab', u'IFA-Labrundvisning'),
(u'nanolab', u'iNANO-labrundvisning'),
(u'koor', u'Koordineringsgruppen'),
(u'korrektur', u'Korrektur'),
(u'latex', u'LaTeX'),
(u'lokaler', u'Lokaler'),
(u'metro', u'Metro'),
(u'parkloeb', u'ParXafari'),
(u'pengeforeningen', u'Pengeforeningen'),
(u'grise', u'Praktiske grise'),
(u'gris', u'Praktiske grise-ansvarlig'),
(u'rkfl3', u'RKFL³'),
(u'rkfw', u'RKFW'),
(u'rus2tur', u'Rus2turs-guide'),
(u'csrusbog', u'Rushåndbog - CS'),
(u'ifarusbog', u'Rushåndbog - IFA'),
(u'matrusbog', u'Rushåndbog - IMF'),
(u'rusteater', u'Rusteater'),
(u'sangbog', u'Sangbog'),
(u'sol', u'SOL'),
(u'sponsor', u'Sponsor'),
(u'sportsdag', u'Sportsdag'),
(u'tutorbog', u'Tutorbog'),
(u'tutorfest', u'Tutorfest'),
(u'dattoe', u'TØ i rusdagene - datalogi'),
(u'fystoe', u'TØ i rusdagene - fysik'),
(u'ittoe', u'TØ i rusdagene - IT'),
(u'moktoe', u'TØ i rusdagene - mat/øk'),
(u'mattoe', u'TØ i rusdagene - matematik'),
(u'nanotoe', u'TØ i rusdagene - nano'),
(u'web', u'Web'),
(u'hacker', u'Wiki'),
(u'oekonomi', u'Økonomi'),
)
