# Generated by Django 2.2.13 on 2024-07-01 12:01

from django.db import migrations, models
import mftutor.gallery.utils


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_auto_20240402_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(blank=True, upload_to=mftutor.gallery.utils.file_name),
        ),
    ]
