# Generated by Django 2.2.13 on 2021-06-30 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confirmation', '0002_confirmation_considerations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmation',
            name='considerations',
        ),
    ]
