# Generated by Django 2.1.7 on 2019-05-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=20, verbose_name='Kaldenavn'),
        ),
    ]
