# Generated by Django 2.2.13 on 2021-03-31 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_tutorprofile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='burBrevSignup',
            field=models.BooleanField(default=False, verbose_name='Tilmeldt Burets Nyhedsbrev'),
        ),
    ]
