# Generated by Django 2.2.13 on 2023-03-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_tutorprofile_burbrevsignup'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='hemmeligSangbogSignup',
            field=models.BooleanField(default=False, verbose_name='Tilmeld hemmelig sangbog'),
        ),
    ]
