# Generated by Django 2.2.13 on 2024-03-02 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_tutorprofile_hemmeligsangbogsignup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorprofile',
            name='hemmeligSangbogSignup',
        ),
    ]
