# Generated by Django 2.2.13 on 2025-03-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0005_remove_tutorprofile_hemmeligsangbogsignup'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='hemmeligSangbogSignup',
            field=models.BooleanField(default=False, verbose_name='Tilmeld hemmelig sangbog'),
        ),
    ]
