# Generated by Django 2.2.13 on 2025-03-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0006_tutorprofile_hemmeligsangbogsignup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorgroup',
            name='handle',
            field=models.CharField(help_text='Bruges i gruppens emailadresse', max_length=30, verbose_name='Kort navn'),
        ),
    ]
