# Generated by Django 2.2.13 on 2025-03-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0007_auto_20250326_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmember',
            name='short_title',
            field=models.CharField(default='form', max_length=50, verbose_name='email titel'),
            preserve_default=False,
        ),
    ]
