from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from ..tutor.auth import tutorbur_required
from .views import ChooseSessionView, NewSessionView, EditSessionView, NotesView, RusListView, ChangeClassView, AjaxChangeClassView, ChangeArrivedView, AjaxChangeArrivedView, UndoView, RusListRPC, HandoutListView, HandoutNewView, HandoutResponseView, HandoutResponseDeleteView, HandoutSummaryView

urlpatterns = patterns('',
    url(r'^new/$', tutorbur_required(NewSessionView.as_view()),
        name='import_session_new'),
    url(r'^(?P<pk>\d+)/$', tutorbur_required(EditSessionView.as_view()),
        name='import_session_edit'),
    url(r'^$', tutorbur_required(ChooseSessionView.as_view()),
        name='import_session_choose'),
    url(r'^list/$', tutorbur_required(RusListView.as_view()),
        name='reg_rus_list'),
    url(r'^list/changeclass/$', tutorbur_required(ChangeClassView.as_view()),
        name='reg_change_class'),
    url(r'^list/changeclass/ajax/$', tutorbur_required(AjaxChangeClassView.as_view()),
        name='reg_change_class_ajax'),
    url(r'^list/changearrived/(?P<pk>\d+)/$', tutorbur_required(ChangeArrivedView.as_view()),
        name='reg_change_arrived'),
    url(r'^list/changearrived/(?P<pk>\d+)/ajax/$', tutorbur_required(AjaxChangeArrivedView.as_view()),
        name='reg_change_arrived_ajax'),
    url(r'^notes/$', tutorbur_required(NotesView.as_view()),
        name='reg_notes'),
    url(r'^undo/(?P<pk>\d+)/$', tutorbur_required(UndoView.as_view()),
        name='reg_undo'),
    url(r'^rpc/$', tutorbur_required(RusListRPC.as_view()),
        name='reg_rpc'),
    url(r'^handout/$', tutorbur_required(HandoutListView.as_view()),
        name='handout_list'),
    url(r'^handout/(?P<handout>\d+)/$', tutorbur_required(HandoutSummaryView.as_view()),
        name='handout_summary'),
    url(r'^handout/new/$', tutorbur_required(HandoutNewView.as_view()),
        name='handout_new'),
    url(r'^handout/(?P<handout>\d+)/(?P<rusclass>[a-z0-9]+)/$', tutorbur_required(HandoutResponseView.as_view()),
        name='handout_response'),
    url(r'^handout/(?P<handout>\d+)/(?P<rusclass>[a-z0-9]+)/delete/$',
        tutorbur_required(HandoutResponseDeleteView.as_view()), name='handout_response_delete'),
)
